### ISSUE TITLE
finalizeAuction without a guard

### ISSUE THREAD

**Issue by bertschneider** [raiden-network/raiden-token#145]
I was just wondering why `finalizeAuction` has no `isOwner` modifier. Shouldn't only the owner be able to finalize the auction? On the other hand one can not bid anymore so it shouldnt't be a problem.

**Comment by loredanacirstea** [comment]
> On the other hand one can not bid anymore so it shouldn't be a problem

Exactly. The auction logic & stages make sure everything is correct.  

Actually, there are reasons to not have `isOwner` as a modifier there. E.g. something happens with the `owner` account and the auction cannot be finalized.
In the current implementation we ensure that we don't have a single point of failure and that anyone can finalize the auction when the auction state permits.

**Comment by loredanacirstea** [comment]
Closing, as this is not an issue. Please reopen if needed and thank you for taking the time to review the contracts.

**Comment by bertschneider** [comment]
That makes sense. Thank you for the fast answer.
