### ISSUE TITLE
Move the transfer of preallocated addresses after the sale is over

### ISSUE THREAD

**Issue by LefterisJP** [raiden-network/raiden-token#48]
At the moment we [transfer](https://github.com/raiden-network/raiden-token/blob/c37fb34b05f85b1633c381d1e547af24b8453089/contracts/token.sol#L248) tokens to preallocated addressses from the very deployment of the token contract.

This is rather bad and can shine a very negative light on us. If we are to go with any preallocated addresses their balances should be kept in an array/mapping and transfers should happen only at the end of the token auction. All people should get their tokens at the same time.

**Comment by loredanacirstea** [comment]
@LefterisJP , this shouldn't be an issue anymore. 
We send the tokens to the wallet now, not to an array of addresses. And it is safer to do this in the beginning than at finalizeAuction time or at the last claimTokens.

**Comment by LefterisJP** [comment]
yes we can, things have changed a lot since I opened the issue.
